package yokai

// curatedProfiles is the hand-written yokai encyclopedia backing
// yokai_of_the_day and list_curated_yokai. Keep entries bilingual:
// English fields feed prose generation, *JA fields keep the lore native.
var curatedProfiles = []Profile{
	{
		Name:        "Kappa",
		NativeName:  "河童",
		Region:      "River valleys across Japan",
		Category:    "Water spirit",
		Summary:     "Mischievous, turtle-backed river dwellers that bargain with humans in exchange for cucumbers or favors.",
		SummaryJA:   "川や沼に棲む、亀の甲羅を背負った悪戯好きの水の妖怪。頭の皿の水が力の源で、キュウリと相撲が大好物。",
		Legends:     []string{"Challenges travellers to sumo bouts by the water's edge", "Known to return politeness with politeness, sometimes to their own downfall"},
		Traits:      []string{"Shell-backed", "Webbed hands", "Cucumber obsession"},
		Motifs:      []string{"Water bargains", "Etiquette", "Harvest rituals"},
		FunFact:     "If you bow deeply to a kappa, it will bow back and spill the life-giving water from its sara (head dish).",
		FunFactJA:   "河童に深くお辞儀をすると、律儀にお辞儀を返して頭の皿の水をこぼしてしまうという。",
		SearchQuery: "河童 妖怪 民話",
		CreativeHooks: []string{
			"Imagine a riverside festival game inspired by a kappa's playful pranks.",
			"Design a collaborative truce between local farmers and a curious kappa.",
		},
	},
	{
		Name:        "Tengu",
		NativeName:  "天狗",
		Region:      "Mountain shrines and deep cedar forests",
		Category:    "Mountain sentinel",
		Summary:     "Avian-nosed martial spirits who guard sacred mountains and challenge arrogant wanderers.",
		SummaryJA:   "高い鼻と翼を持つ山の護り手。慢心した旅人や僧を懲らしめ、見込んだ者には剣術を授けるという。",
		Legends:     []string{"Teaches swordplay to worthy disciples", "Kidnaps boastful priests to humble them"},
		Traits:      []string{"Command over wind gusts", "Master swordsmen", "Prideful guardians"},
		Motifs:      []string{"Discipline", "Humility", "Mountain austerity"},
		FunFact:     "Some medieval stories claim tengu invented the fan that can summon storms with a single flap.",
		FunFactJA:   "一振りで嵐を呼ぶ羽団扇は天狗の発明だと語る中世の物語もある。",
		SearchQuery: "天狗 修験道 伝承",
		CreativeHooks: []string{
			"Stage a duel where a tengu tests a traveller's resolve atop a precarious bridge.",
			"Create a secret tengu dojo hidden behind masked cedar trees.",
		},
	},
	{
		Name:        "Yuki-onna",
		NativeName:  "雪女",
		Region:      "Snowbound provinces of northern Honshu",
		Category:    "Snow phantom",
		Summary:     "Ethereal women cloaked in frost who appear during blizzards, balancing mercy and chill judgment.",
		SummaryJA:   "吹雪の夜に現れる氷のように美しい女性の妖怪。慈悲と冷徹さをあわせ持ち、心優しい者を見逃すこともある。",
		Legends:     []string{"Spare kind-hearted woodcutters who share warmth", "Vanish at sunrise, leaving only drifting snowflakes"},
		Traits:      []string{"Breath colder than night", "Gliding footsteps", "Moonlit presence"},
		Motifs:      []string{"Impermanence", "Winter trials", "Frozen bargains"},
		FunFact:     "Some tales describe the Yuki-onna carrying a baby made of ice to test a traveller's compassion.",
		FunFactJA:   "旅人の情けを試すため、氷でできた赤子を抱いて現れるという言い伝えも残る。",
		SearchQuery: "雪女 逸話 民俗学",
		CreativeHooks: []string{
			"Compose a scene where a Yuki-onna negotiates a fragile truce with spring itself.",
			"Illustrate snowflake sigils that mark the path to a Yuki-onna's hidden glade.",
		},
	},
	{
		Name:        "Kitsune",
		NativeName:  "九尾の狐",
		Region:      "Shrines and mist-laden plains",
		Category:    "Mystic fox",
		Summary:     "Shape-shifting fox spirits credited with trickery, wisdom, and occasionally saving entire provinces.",
		SummaryJA:   "変化と幻術を操る狐の霊。悪戯もすれば知恵で国を救いもする、稲荷神の使いとしても知られる存在。",
		Legends:     []string{"Transforms into a dazzling performer to expose corruption", "Serves as messengers to the deity Inari"},
		Traits:      []string{"Illusory flames", "Multiple tails", "Silver-tongued"},
		Motifs:      []string{"Transformation", "Hidden intentions", "Sacred rice granaries"},
		FunFact:     "Folklore says each tail a kitsune grows grants a century of experience and sharpens its magic.",
		FunFactJA:   "尻尾が一本増えるごとに百年分の経験と、より強い妖力が宿るとされる。",
		SearchQuery: "九尾狐 伝説 稲荷",
		CreativeHooks: []string{
			"Imagine a kitsune producing illusions to orchestrate a moonlit festival.",
			"Plot a political thriller where a kitsune advisor balances trickery with loyalty.",
		},
	},
	{
		Name:        "Bakeneko",
		NativeName:  "化け猫",
		Region:      "Castle towns and tea houses across Japan",
		Category:    "Shape-shifting beast",
		Summary:     "Once-domestic cats who, after long years, gain the uncanny ability to mimic human life and speech.",
		SummaryJA:   "長い年月を生きた飼い猫が化けたもの。人の言葉を話し、手ぬぐいを被って踊るなど、人間の暮らしを真似る。",
		Legends:     []string{"Disguises itself as an innkeeper to run a midnight salon", "Dances with a towel wrapped on its head in the glow of lantern light"},
		Traits:      []string{"Forked tail", "Human-like speech", "Illusory shadows"},
		Motifs:      []string{"Transformation", "Domestic secrets", "Nighttime revelry"},
		FunFact:     "People once believed a cat's tail should be shortened to prevent it from becoming a bakeneko.",
		FunFactJA:   "猫が化け猫にならないよう、尻尾を短く切る風習があったと伝えられる。",
		SearchQuery: "化け猫 怪談 江戸",
		CreativeHooks: []string{
			"Script a late-night tea ceremony hosted by a refined bakeneko.",
			"Invent a jazz club run by century-old cats trading gossip for secrets.",
		},
	},
	{
		Name:        "Nurikabe",
		NativeName:  "ぬりかべ",
		Region:      "Winding roads of Kyushu",
		Category:    "Trickster wall",
		Summary:     "Invisible wall yokai that halts travellers, forcing them to rethink their route or wait until dawn.",
		SummaryJA:   "夜道で突然行く手を阻む見えない壁の妖怪。棒で足元を払うと消えるが、上の方を叩いても効かないという。",
		Legends:     []string{"Blocks the path of impatient samurai, yet lets lost children pass", "Said to fade if tapped with a stick near the ground"},
		Traits:      []string{"Immovable presence", "Invisible bulk", "Silence"},
		Motifs:      []string{"Patience", "Detours", "Hidden thresholds"},
		FunFact:     "Some Edo-period maps warn, tongue-in-cheek, of nurikabe hotspots to explain mysteriously long journeys.",
		FunFactJA:   "江戸時代には、旅がやけに長引いた言い訳として「ぬりかべの仕業」と冗談めかして語られたという。",
		SearchQuery: "ぬりかべ 伝説 道中",
		CreativeHooks: []string{
			"Design an escape-room puzzle where the walls are mischievous nurikabe spirits.",
			"Write a travelogue that becomes an allegory about embracing detours.",
		},
	},
	{
		Name:        "Rokurokubi",
		NativeName:  "ろくろ首",
		Region:      "Edo-period inns and waystations",
		Category:    "Nightly wanderer",
		Summary:     "By day they appear human; by night their necks stretch impossibly long, roaming halls in search of stories.",
		SummaryJA:   "昼間は普通の人間に見えるが、夜になると首が伸びて家中を徘徊する妖怪。行灯の油を舐めるとも噂される。",
		Legends:     []string{"Eavesdrops on sleeping guests to devour their whispered secrets", "Falls for a traveller who notices her dual life"},
		Traits:      []string{"Extendable neck", "Hypnotic gaze", "Nocturnal curiosity"},
		Motifs:      []string{"Hidden identities", "Nightly vigilance", "Story gathering"},
		FunFact:     "Old tales describe rokurokubi sending their heads to scout ahead while the body continues household chores.",
		FunFactJA:   "体が家事を続けている間に、首だけを先へ偵察に飛ばすというろくろ首の話も残っている。",
		SearchQuery: "ろくろ首 怪異 怪談",
		CreativeHooks: []string{
			"Compose a mystery solved by a rokurokubi who hears clues in the rafters.",
			"Storyboard a comic where elongated necks become a whimsical superpower.",
		},
	},
	{
		Name:        "Umi-bozu",
		NativeName:  "海坊主",
		Region:      "Storm-swept coasts of western Japan",
		Category:    "Sea apparition",
		Summary:     "Enigmatic, towering figures that rise from turbulent seas, tipping ships unless appeased with lantern light.",
		SummaryJA:   "荒れた海から突如現れる黒く巨大な坊主頭の怪異。船を沈めるが、灯りや油を捧げると鎮まるという。",
		Legends:     []string{"Silences entire crews before crushing their masts", "Seeks offerings of oil to calm the waves"},
		Traits:      []string{"Towering silhouette", "Ink-black skin", "Tempest caller"},
		Motifs:      []string{"Respect for the sea", "Offerings", "Sailors' superstition"},
		FunFact:     "Fisherfolk once feared whispering the umi-bozu's name, believing it summoned waves tall enough to swallow lighthouses.",
		FunFactJA:   "海坊主の名を口にするだけで灯台を飲み込むほどの大波が来ると信じ、漁師たちはその名を囁くことさえ恐れた。",
		SearchQuery: "海坊主 海難 民話",
		CreativeHooks: []string{
			"Plot a maritime negotiation between lighthouse keepers and a lonely umi-bozu.",
			"Create ambient sea shanties that keep the umi-bozu lulled to sleep.",
		},
	},
	{
		Name:        "Gashadokuro",
		NativeName:  "餓者髑髏",
		Region:      "Battlefields and famine-struck villages",
		Category:    "Colossal skeleton",
		Summary:     "Gigantic skeleton spirits formed from the restless dead, stalking the countryside until pacified with ritual bells.",
		SummaryJA:   "戦や飢饉で弔われなかった死者の骨が集まってできた巨大な骸骨。深夜に現れ、耳鳴りがその接近の合図とされる。",
		Legends:     []string{"Materializes at midnight to devour lone travellers", "Announced by a ringing in the ears before it strikes"},
		Traits:      []string{"Skull taller than treetops", "Bone-rattling footsteps", "Relentless hunger"},
		Motifs:      []string{"Reckoning", "Remembrance", "Famine tales"},
		FunFact:     "Some modern retellings convert the gashadokuro into gentle guardians once their bones are respectfully enshrined.",
		FunFactJA:   "現代の再話には、骨を丁重に祀れば村の守り神に変わるという優しい結末も生まれている。",
		SearchQuery: "餓者髑髏 怪物 伝説",
		CreativeHooks: []string{
			"Write a requiem that persuades a gashadokuro to become a village protector.",
			"Design glowing talismans that disrupt the skeleton's eerie ear-ringing omen.",
		},
	},
	{
		Name:        "Amabie",
		NativeName:  "アマビエ",
		Region:      "Kumamoto's coastal waters",
		Category:    "Prophetic being",
		Summary:     "A mermaid-like oracle who surfaces to warn of plagues and promises good harvests if its image is shared.",
		SummaryJA:   "海から現れて疫病を予言し、「私の姿を描き写して人に見せよ」と告げたと伝わる熊本の予言獣。",
		Legends:     []string{"Emerges shining from the sea to deliver prophecies", "Inspires villagers to sketch its likeness for protection"},
		Traits:      []string{"Beaked face", "Glowing scales", "Future sight"},
		Motifs:      []string{"Hope", "Community art", "Healing"},
		FunFact:     "During modern outbreaks, Japanese artists revived the tradition of drawing Amabie as a charm against illness.",
		FunFactJA:   "令和の感染症流行時には、姿を描いて共有する「アマビエチャレンジ」としてSNSで復活した。",
		SearchQuery: "アマビエ 予言 疫病",
		CreativeHooks: []string{
			"Curate a community mural project led by Amabie fans across eras.",
			"Imagine Amabie livestreaming predictions to lighthouse keepers.",
		},
	},
	{
		Name:        "Zashiki-warashi",
		NativeName:  "座敷童子",
		Region:      "Old family homes of Tohoku, especially Iwate",
		Category:    "House spirit",
		Summary:     "Childlike guardian spirits dwelling in tatami rooms, showering fortune on households that treat them kindly.",
		SummaryJA:   "座敷や蔵に棲みつく童子姿の家神。住み着いた家には幸運をもたらすが、去られると家運が傾くと伝わる。",
		Legends:     []string{"Leaves tiny footprints in scattered ashes overnight", "Fortune follows the household it inhabits and fades when it departs"},
		Traits:      []string{"Bobbed hair", "Playful footsteps", "Shy giggles"},
		Motifs:      []string{"Hospitality", "Household fortune", "Innocence"},
		FunFact:     "Some inns in Iwate keep rooms where guests hope to glimpse a zashiki-warashi, with bookings stretching years ahead.",
		FunFactJA:   "岩手県には座敷童子に会えると評判の旅館があり、その部屋は数年先まで予約が埋まるほどの人気だという。",
		SearchQuery: "座敷童子 岩手 伝承",
		CreativeHooks: []string{
			"Write a family drama where renovating an old home risks evicting its zashiki-warashi.",
			"Design a cozy game about earning the trust of an unseen playmate room by room.",
		},
	},
	{
		Name:        "Nue",
		NativeName:  "鵺",
		Region:      "Imperial capital of Kyoto",
		Category:    "Chimera omen",
		Summary:     "A chimera with a monkey's face, tanuki's body, tiger's limbs, and serpent tail whose night cry heralded misfortune at court.",
		SummaryJA:   "猿の顔、狸の胴、虎の手足、蛇の尾を持つ怪鳥。夜ごと帝を悩ませ、源頼政に射落とされた『平家物語』の怪異。",
		Legends:     []string{"Tormented Emperor Konoe beneath black clouds until Minamoto no Yorimasa shot it from the night sky", "Its body was set adrift down the river in a dugout boat to carry the curse away"},
		Traits:      []string{"Monkey's face", "Tiger's limbs", "Serpent tail"},
		Motifs:      []string{"Ill omens", "Hybrid identity", "Courtly dread"},
		FunFact:     "The nue is named for a real bird, the scaly thrush, whose mournful night call was itself considered an evil omen.",
		FunFactJA:   "「ぬえ」の名は夜に物悲しく鳴く鳥トラツグミに由来し、正体不明の人物を指す「鵺的」という言葉まで生んだ。",
		SearchQuery: "鵺 平家物語 退治",
		CreativeHooks: []string{
			"Compose a courtly mystery where an unseen cry sickens the capital night after night.",
			"Reimagine the nue as a misunderstood patchwork creature searching for its true form.",
		},
	},
	{
		Name:        "Kamaitachi",
		NativeName:  "鎌鼬",
		Region:      "Snowy plains of the Koshin'etsu region",
		Category:    "Wind beast",
		Summary:     "Sickle-clawed weasels riding whirlwinds in trios — one topples, one cuts, one salves — leaving painless wounds behind.",
		SummaryJA:   "つむじ風に乗って現れるイタチの妖怪。三匹一組で、転ばせ、切りつけ、薬を塗って去るため、傷は痛まないという。",
		Legends:     []string{"Rides whirlwinds as a trio: the first knocks travellers down, the second cuts, the third heals", "Blamed for mysterious painless gashes that appear after cold gusts"},
		Traits:      []string{"Sickle-like claws", "Whirlwind speed", "Invisible strikes"},
		Motifs:      []string{"Winter winds", "Teamwork", "Painless wounds"},
		FunFact:     "In some regions people carried old calendars as charms, believing the paper could ward off kamaitachi cuts.",
		FunFactJA:   "地方によっては古暦を懐に入れておくと鎌鼬の切り傷を防げるという、紙のお守りの風習があった。",
		SearchQuery: "鎌鼬 つむじ風 伝承",
		CreativeHooks: []string{
			"Choreograph a heist executed by three weasel spirits within a single gust of wind.",
			"Sketch a rivalry between a kamaitachi trio and a modern wind-turbine town.",
		},
	},
	{
		Name:        "Ittan-momen",
		NativeName:  "一反木綿",
		Region:      "Kimotsuki district of Kagoshima",
		Category:    "Flying cloth",
		Summary:     "A ten-metre strip of white cotton that flutters through dusk skies and wraps itself around late-night walkers.",
		SummaryJA:   "夕暮れの空をひらひらと飛ぶ一反（約10メートル）の白い木綿。夜道を歩く人の顔に巻きつくと伝わる鹿児島の妖怪。",
		Legends:     []string{"Flutters out of the dusk to wrap around the faces of night walkers", "Kagoshima tales say it can be repelled with a blade or a well-timed bite"},
		Traits:      []string{"Ten-metre cotton body", "Silent flight", "Sudden embrace"},
		Motifs:      []string{"Twilight skies", "Everyday objects turned uncanny", "Flight"},
		FunFact:     "GeGeGe no Kitaro recast the ittan-momen as a heroic flying companion, making it one of Japan's best-loved yokai.",
		FunFactJA:   "『ゲゲゲの鬼太郎』では鬼太郎たちを乗せて空を飛ぶ頼れる仲間として描かれ、一躍人気者になった。",
		SearchQuery: "一反木綿 鹿児島 妖怪",
		CreativeHooks: []string{
			"Draft an aerial courier service run by reformed ittan-momen.",
			"Animate a bolt of cloth learning to be a hero's cape instead of a prankster.",
		},
	},
	{
		Name:        "Amanojaku",
		NativeName:  "天邪鬼",
		Region:      "Temple gates and mountain passes across Japan",
		Category:    "Contrarian imp",
		Summary:     "A perverse imp that reads hearts and goads people into doing the opposite of their true wishes.",
		SummaryJA:   "人の心を読み、わざと逆のことをさせようとするひねくれ者の小鬼。仏堂では四天王像に踏みつけられる姿で知られる。",
		Legends:     []string{"Provokes people into blurting out hidden desires, then twists them", "In the tale of Uriko-hime, it deceives and impersonates the melon princess"},
		Traits:      []string{"Heart-reading", "Contrary whispers", "Small horned frame"},
		Motifs:      []string{"Contrariness", "Temptation", "Guardians' triumph"},
		FunFact:     "Amanojaku lives on in everyday Japanese: calling someone an 'amanojaku' still means they are a natural contrarian.",
		FunFactJA:   "ひねくれ者を指す「あまのじゃく」という言葉として、現代の日常会話にも生き続けている。",
		SearchQuery: "天邪鬼 民話 瓜子姫",
		CreativeHooks: []string{
			"Write a negotiation where the only way to win is to wish for the opposite.",
			"Design a puzzle boss that mirrors and inverts the player's every choice.",
		},
	},
}
