package yokai

// curatedProfiles is the hand-written yokai encyclopedia backing
// yokai_of_the_day and list_curated_yokai. Keep entries bilingual:
// English fields feed prose generation, *JA fields keep the lore native.
var curatedProfiles = []Profile{
	{
		Name:        "Kappa",
		NativeName:  "河童",
		Region:      "River valleys across Japan",
		Category:    "Water spirit",
		Summary:     "Mischievous, turtle-backed river dwellers that bargain with humans in exchange for cucumbers or favors.",
		SummaryJA:   "川や沼に棲む、亀の甲羅を背負った悪戯好きの水の妖怪。頭の皿の水が力の源で、キュウリと相撲が大好物。",
		Legends:     []string{"Challenges travellers to sumo bouts by the water's edge", "Known to return politeness with politeness, sometimes to their own downfall"},
		Traits:      []string{"Shell-backed", "Webbed hands", "Cucumber obsession"},
		Motifs:      []string{"Water bargains", "Etiquette", "Harvest rituals"},
		FunFact:     "If you bow deeply to a kappa, it will bow back and spill the life-giving water from its sara (head dish).",
		FunFactJA:   "河童に深くお辞儀をすると、律儀にお辞儀を返して頭の皿の水をこぼしてしまうという。",
		SearchQuery: "河童 妖怪 民話",
		CreativeHooks: []string{
			"Imagine a riverside festival game inspired by a kappa's playful pranks.",
			"Design a collaborative truce between local farmers and a curious kappa.",
		},
	},
	{
		Name:        "Tengu",
		NativeName:  "天狗",
		Region:      "Mountain shrines and deep cedar forests",
		Category:    "Mountain sentinel",
		Summary:     "Avian-nosed martial spirits who guard sacred mountains and challenge arrogant wanderers.",
		SummaryJA:   "高い鼻と翼を持つ山の護り手。慢心した旅人や僧を懲らしめ、見込んだ者には剣術を授けるという。",
		Legends:     []string{"Teaches swordplay to worthy disciples", "Kidnaps boastful priests to humble them"},
		Traits:      []string{"Command over wind gusts", "Master swordsmen", "Prideful guardians"},
		Motifs:      []string{"Discipline", "Humility", "Mountain austerity"},
		FunFact:     "Some medieval stories claim tengu invented the fan that can summon storms with a single flap.",
		FunFactJA:   "一振りで嵐を呼ぶ羽団扇は天狗の発明だと語る中世の物語もある。",
		SearchQuery: "天狗 修験道 伝承",
		CreativeHooks: []string{
			"Stage a duel where a tengu tests a traveller's resolve atop a precarious bridge.",
			"Create a secret tengu dojo hidden behind masked cedar trees.",
		},
	},
	{
		Name:        "Yuki-onna",
		NativeName:  "雪女",
		Region:      "Snowbound provinces of northern Honshu",
		Category:    "Snow phantom",
		Summary:     "Ethereal women cloaked in frost who appear during blizzards, balancing mercy and chill judgment.",
		SummaryJA:   "吹雪の夜に現れる氷のように美しい女性の妖怪。慈悲と冷徹さをあわせ持ち、心優しい者を見逃すこともある。",
		Legends:     []string{"Spare kind-hearted woodcutters who share warmth", "Vanish at sunrise, leaving only drifting snowflakes"},
		Traits:      []string{"Breath colder than night", "Gliding footsteps", "Moonlit presence"},
		Motifs:      []string{"Impermanence", "Winter trials", "Frozen bargains"},
		FunFact:     "Some tales describe the Yuki-onna carrying a baby made of ice to test a traveller's compassion.",
		FunFactJA:   "旅人の情けを試すため、氷でできた赤子を抱いて現れるという言い伝えも残る。",
		SearchQuery: "雪女 逸話 民俗学",
		CreativeHooks: []string{
			"Compose a scene where a Yuki-onna negotiates a fragile truce with spring itself.",
			"Illustrate snowflake sigils that mark the path to a Yuki-onna's hidden glade.",
		},
	},
	{
		Name:        "Kitsune",
		NativeName:  "九尾の狐",
		Region:      "Shrines and mist-laden plains",
		Category:    "Mystic fox",
		Summary:     "Shape-shifting fox spirits credited with trickery, wisdom, and occasionally saving entire provinces.",
		SummaryJA:   "変化と幻術を操る狐の霊。悪戯もすれば知恵で国を救いもする、稲荷神の使いとしても知られる存在。",
		Legends:     []string{"Transforms into a dazzling performer to expose corruption", "Serves as messengers to the deity Inari"},
		Traits:      []string{"Illusory flames", "Multiple tails", "Silver-tongued"},
		Motifs:      []string{"Transformation", "Hidden intentions", "Sacred rice granaries"},
		FunFact:     "Folklore says each tail a kitsune grows grants a century of experience and sharpens its magic.",
		FunFactJA:   "尻尾が一本増えるごとに百年分の経験と、より強い妖力が宿るとされる。",
		SearchQuery: "九尾狐 伝説 稲荷",
		CreativeHooks: []string{
			"Imagine a kitsune producing illusions to orchestrate a moonlit festival.",
			"Plot a political thriller where a kitsune advisor balances trickery with loyalty.",
		},
	},
	{
		Name:        "Bakeneko",
		NativeName:  "化け猫",
		Region:      "Castle towns and tea houses across Japan",
		Category:    "Shape-shifting beast",
		Summary:     "Once-domestic cats who, after long years, gain the uncanny ability to mimic human life and speech.",
		SummaryJA:   "長い年月を生きた飼い猫が化けたもの。人の言葉を話し、手ぬぐいを被って踊るなど、人間の暮らしを真似る。",
		Legends:     []string{"Disguises itself as an innkeeper to run a midnight salon", "Dances with a towel wrapped on its head in the glow of lantern light"},
		Traits:      []string{"Forked tail", "Human-like speech", "Illusory shadows"},
		Motifs:      []string{"Transformation", "Domestic secrets", "Nighttime revelry"},
		FunFact:     "People once believed a cat's tail should be shortened to prevent it from becoming a bakeneko.",
		FunFactJA:   "猫が化け猫にならないよう、尻尾を短く切る風習があったと伝えられる。",
		SearchQuery: "化け猫 怪談 江戸",
		CreativeHooks: []string{
			"Script a late-night tea ceremony hosted by a refined bakeneko.",
			"Invent a jazz club run by century-old cats trading gossip for secrets.",
		},
	},
	{
		Name:        "Nurikabe",
		NativeName:  "ぬりかべ",
		Region:      "Winding roads of Kyushu",
		Category:    "Trickster wall",
		Summary:     "Invisible wall yokai that halts travellers, forcing them to rethink their route or wait until dawn.",
		SummaryJA:   "夜道で突然行く手を阻む見えない壁の妖怪。棒で足元を払うと消えるが、上の方を叩いても効かないという。",
		Legends:     []string{"Blocks the path of impatient samurai, yet lets lost children pass", "Said to fade if tapped with a stick near the ground"},
		Traits:      []string{"Immovable presence", "Invisible bulk", "Silence"},
		Motifs:      []string{"Patience", "Detours", "Hidden thresholds"},
		FunFact:     "Some Edo-period maps warn, tongue-in-cheek, of nurikabe hotspots to explain mysteriously long journeys.",
		FunFactJA:   "江戸時代には、旅がやけに長引いた言い訳として「ぬりかべの仕業」と冗談めかして語られたという。",
		SearchQuery: "ぬりかべ 伝説 道中",
		CreativeHooks: []string{
			"Design an escape-room puzzle where the walls are mischievous nurikabe spirits.",
			"Write a travelogue that becomes an allegory about embracing detours.",
		},
	},
	{
		Name:        "Rokurokubi",
		NativeName:  "ろくろ首",
		Region:      "Edo-period inns and waystations",
		Category:    "Nightly wanderer",
		Summary:     "By day they appear human; by night their necks stretch impossibly long, roaming halls in search of stories.",
		SummaryJA:   "昼間は普通の人間に見えるが、夜になると首が伸びて家中を徘徊する妖怪。行灯の油を舐めるとも噂される。",
		Legends:     []string{"Eavesdrops on sleeping guests to devour their whispered secrets", "Falls for a traveller who notices her dual life"},
		Traits:      []string{"Extendable neck", "Hypnotic gaze", "Nocturnal curiosity"},
		Motifs:      []string{"Hidden identities", "Nightly vigilance", "Story gathering"},
		FunFact:     "Old tales describe rokurokubi sending their heads to scout ahead while the body continues household chores.",
		FunFactJA:   "体が家事を続けている間に、首だけを先へ偵察に飛ばすというろくろ首の話も残っている。",
		SearchQuery: "ろくろ首 怪異 怪談",
		CreativeHooks: []string{
			"Compose a mystery solved by a rokurokubi who hears clues in the rafters.",
			"Storyboard a comic where elongated necks become a whimsical superpower.",
		},
	},
	{
		Name:        "Umibozu",
		NativeName:  "海坊主",
		Region:      "Storm-swept coasts of western Japan",
		Category:    "Sea apparition",
		Summary:     "Enigmatic, towering figures that rise from turbulent seas, tipping ships unless appeased with lantern light.",
		SummaryJA:   "荒れた海から突如現れる黒く巨大な坊主頭の怪異。船を沈めるが、灯りや油を捧げると鎮まるという。",
		Legends:     []string{"Silences entire crews before crushing their masts", "Seeks offerings of oil to calm the waves"},
		Traits:      []string{"Towering silhouette", "Ink-black skin", "Tempest caller"},
		Motifs:      []string{"Respect for the sea", "Offerings", "Sailors' superstition"},
		FunFact:     "Fisherfolk once feared whispering the umi-bozu's name, believing it summoned waves tall enough to swallow lighthouses.",
		FunFactJA:   "海坊主の名を口にするだけで灯台を飲み込むほどの大波が来ると信じ、漁師たちはその名を囁くことさえ恐れた。",
		SearchQuery: "海坊主 海難 民話",
		CreativeHooks: []string{
			"Plot a maritime negotiation between lighthouse keepers and a lonely umi-bozu.",
			"Create ambient sea shanties that keep the umi-bozu lulled to sleep.",
		},
	},
	{
		Name:        "Gashadokuro",
		NativeName:  "餓者髑髏",
		Region:      "Battlefields and famine-struck villages",
		Category:    "Colossal skeleton",
		Summary:     "Gigantic skeleton spirits formed from the restless dead, stalking the countryside until pacified with ritual bells.",
		SummaryJA:   "戦や飢饉で弔われなかった死者の骨が集まってできた巨大な骸骨。深夜に現れ、耳鳴りがその接近の合図とされる。",
		Legends:     []string{"Materializes at midnight to devour lone travellers", "Announced by a ringing in the ears before it strikes"},
		Traits:      []string{"Skull taller than treetops", "Bone-rattling footsteps", "Relentless hunger"},
		Motifs:      []string{"Reckoning", "Remembrance", "Famine tales"},
		FunFact:     "Some modern retellings convert the gashadokuro into gentle guardians once their bones are respectfully enshrined.",
		FunFactJA:   "現代の再話には、骨を丁重に祀れば村の守り神に変わるという優しい結末も生まれている。",
		SearchQuery: "餓者髑髏 怪物 伝説",
		CreativeHooks: []string{
			"Write a requiem that persuades a gashadokuro to become a village protector.",
			"Design glowing talismans that disrupt the skeleton's eerie ear-ringing omen.",
		},
	},
	{
		Name:        "Amabie",
		NativeName:  "アマビエ",
		Region:      "Kumamoto's coastal waters",
		Category:    "Prophetic being",
		Summary:     "A mermaid-like oracle who surfaces to warn of plagues and promises good harvests if its image is shared.",
		SummaryJA:   "海から現れて疫病を予言し、「私の姿を描き写して人に見せよ」と告げたと伝わる熊本の予言獣。",
		Legends:     []string{"Emerges shining from the sea to deliver prophecies", "Inspires villagers to sketch its likeness for protection"},
		Traits:      []string{"Beaked face", "Glowing scales", "Future sight"},
		Motifs:      []string{"Hope", "Community art", "Healing"},
		FunFact:     "During modern outbreaks, Japanese artists revived the tradition of drawing Amabie as a charm against illness.",
		FunFactJA:   "令和の感染症流行時には、姿を描いて共有する「アマビエチャレンジ」としてSNSで復活した。",
		SearchQuery: "アマビエ 予言 疫病",
		CreativeHooks: []string{
			"Curate a community mural project led by Amabie fans across eras.",
			"Imagine Amabie livestreaming predictions to lighthouse keepers.",
		},
	},
	{
		Name:        "Zashiki-warashi",
		NativeName:  "座敷童子",
		Region:      "Old family homes of Tohoku, especially Iwate",
		Category:    "House spirit",
		Summary:     "Childlike guardian spirits dwelling in tatami rooms, showering fortune on households that treat them kindly.",
		SummaryJA:   "座敷や蔵に棲みつく童子姿の家神。住み着いた家には幸運をもたらすが、去られると家運が傾くと伝わる。",
		Legends:     []string{"Leaves tiny footprints in scattered ashes overnight", "Fortune follows the household it inhabits and fades when it departs"},
		Traits:      []string{"Bobbed hair", "Playful footsteps", "Shy giggles"},
		Motifs:      []string{"Hospitality", "Household fortune", "Innocence"},
		FunFact:     "Some inns in Iwate keep rooms where guests hope to glimpse a zashiki-warashi, with bookings stretching years ahead.",
		FunFactJA:   "岩手県には座敷童子に会えると評判の旅館があり、その部屋は数年先まで予約が埋まるほどの人気だという。",
		SearchQuery: "座敷童子 岩手 伝承",
		CreativeHooks: []string{
			"Write a family drama where renovating an old home risks evicting its zashiki-warashi.",
			"Design a cozy game about earning the trust of an unseen playmate room by room.",
		},
	},
	{
		Name:        "Nue",
		NativeName:  "鵺",
		Region:      "Imperial capital of Kyoto",
		Category:    "Chimera omen",
		Summary:     "A chimera with a monkey's face, tanuki's body, tiger's limbs, and serpent tail whose night cry heralded misfortune at court.",
		SummaryJA:   "猿の顔、狸の胴、虎の手足、蛇の尾を持つ怪鳥。夜ごと帝を悩ませ、源頼政に射落とされた『平家物語』の怪異。",
		Legends:     []string{"Tormented Emperor Konoe beneath black clouds until Minamoto no Yorimasa shot it from the night sky", "Its body was set adrift down the river in a dugout boat to carry the curse away"},
		Traits:      []string{"Monkey's face", "Tiger's limbs", "Serpent tail"},
		Motifs:      []string{"Ill omens", "Hybrid identity", "Courtly dread"},
		FunFact:     "The nue is named for a real bird, the scaly thrush, whose mournful night call was itself considered an evil omen.",
		FunFactJA:   "「ぬえ」の名は夜に物悲しく鳴く鳥トラツグミに由来し、正体不明の人物を指す「鵺的」という言葉まで生んだ。",
		SearchQuery: "鵺 平家物語 退治",
		CreativeHooks: []string{
			"Compose a courtly mystery where an unseen cry sickens the capital night after night.",
			"Reimagine the nue as a misunderstood patchwork creature searching for its true form.",
		},
	},
	{
		Name:        "Kamaitachi",
		NativeName:  "鎌鼬",
		Region:      "Snowy plains of the Koshin'etsu region",
		Category:    "Wind beast",
		Summary:     "Sickle-clawed weasels riding whirlwinds in trios — one topples, one cuts, one salves — leaving painless wounds behind.",
		SummaryJA:   "つむじ風に乗って現れるイタチの妖怪。三匹一組で、転ばせ、切りつけ、薬を塗って去るため、傷は痛まないという。",
		Legends:     []string{"Rides whirlwinds as a trio: the first knocks travellers down, the second cuts, the third heals", "Blamed for mysterious painless gashes that appear after cold gusts"},
		Traits:      []string{"Sickle-like claws", "Whirlwind speed", "Invisible strikes"},
		Motifs:      []string{"Winter winds", "Teamwork", "Painless wounds"},
		FunFact:     "In some regions people carried old calendars as charms, believing the paper could ward off kamaitachi cuts.",
		FunFactJA:   "地方によっては古暦を懐に入れておくと鎌鼬の切り傷を防げるという、紙のお守りの風習があった。",
		SearchQuery: "鎌鼬 つむじ風 伝承",
		CreativeHooks: []string{
			"Choreograph a heist executed by three weasel spirits within a single gust of wind.",
			"Sketch a rivalry between a kamaitachi trio and a modern wind-turbine town.",
		},
	},
	{
		Name:        "Ittan-momen",
		NativeName:  "一反木綿",
		Region:      "Kimotsuki district of Kagoshima",
		Category:    "Flying cloth",
		Summary:     "A ten-metre strip of white cotton that flutters through dusk skies and wraps itself around late-night walkers.",
		SummaryJA:   "夕暮れの空をひらひらと飛ぶ一反（約10メートル）の白い木綿。夜道を歩く人の顔に巻きつくと伝わる鹿児島の妖怪。",
		Legends:     []string{"Flutters out of the dusk to wrap around the faces of night walkers", "Kagoshima tales say it can be repelled with a blade or a well-timed bite"},
		Traits:      []string{"Ten-metre cotton body", "Silent flight", "Sudden embrace"},
		Motifs:      []string{"Twilight skies", "Everyday objects turned uncanny", "Flight"},
		FunFact:     "GeGeGe no Kitaro recast the ittan-momen as a heroic flying companion, making it one of Japan's best-loved yokai.",
		FunFactJA:   "『ゲゲゲの鬼太郎』では鬼太郎たちを乗せて空を飛ぶ頼れる仲間として描かれ、一躍人気者になった。",
		SearchQuery: "一反木綿 鹿児島 妖怪",
		CreativeHooks: []string{
			"Draft an aerial courier service run by reformed ittan-momen.",
			"Animate a bolt of cloth learning to be a hero's cape instead of a prankster.",
		},
	},
	{
		Name:        "Amanojaku",
		NativeName:  "天邪鬼",
		Region:      "Temple gates and mountain passes across Japan",
		Category:    "Contrarian imp",
		Summary:     "A perverse imp that reads hearts and goads people into doing the opposite of their true wishes.",
		SummaryJA:   "人の心を読み、わざと逆のことをさせようとするひねくれ者の小鬼。仏堂では四天王像に踏みつけられる姿で知られる。",
		Legends:     []string{"Provokes people into blurting out hidden desires, then twists them", "In the tale of Uriko-hime, it deceives and impersonates the melon princess"},
		Traits:      []string{"Heart-reading", "Contrary whispers", "Small horned frame"},
		Motifs:      []string{"Contrariness", "Temptation", "Guardians' triumph"},
		FunFact:     "Amanojaku lives on in everyday Japanese: calling someone an 'amanojaku' still means they are a natural contrarian.",
		FunFactJA:   "ひねくれ者を指す「あまのじゃく」という言葉として、現代の日常会話にも生き続けている。",
		SearchQuery: "天邪鬼 民話 瓜子姫",
		CreativeHooks: []string{
			"Write a negotiation where the only way to win is to wish for the opposite.",
			"Design a puzzle boss that mirrors and inverts the player's every choice.",
		},
	},
	{
		Name:        "Nopperabou",
		NativeName:  "のっぺらぼう",
		Region:      "Roads and lonely paths across Japan",
		Category:    "Faceless phantom",
		Summary:     "A human-shaped apparition whose face is a blank expanse of skin, startling travellers who expect ordinary features.",
		SummaryJA:   "人の姿をしながら顔がのっぺりと平面の妖怪。道で声をかけた相手が振り向くと、そこには顔がない。",
		Legends:     []string{"Appears as a familiar stranger before revealing its blank face", "Sometimes a second nopperabou waits further down the road"},
		Traits:      []string{"Blank face", "Calm voice", "Night-road encounters"},
		Motifs:      []string{"Identity", "Fear of the unknown", "Mirrors and recognition"},
		FunFact:     "Many classic kaidan end with the horrified traveller meeting another faceless figure at home or at an inn.",
		FunFactJA:   "家に逃げ帰っても、待っていた家族や宿の主人まで顔がない、という落ちの怪談が多い。",
		SearchQuery: "のっぺらぼう 怪談",
		CreativeHooks: []string{
			"Write a mystery where only reflections still have faces.",
			"Design a city whose citizens gradually lose their features overnight.",
		},
	},
	{
		Name:        "Akaname",
		NativeName:  "垢嘗",
		Region:      "Bathhouses and neglected rooms",
		Category:    "Filth licker",
		Summary:     "A long-tongued yokai that creeps into dirty bathrooms to lick up grime, a living caution for unclean places.",
		SummaryJA:   "長い舌で風呂や不潔な場所の垢を舐める妖怪。清潔を怠ると現れる、という戒めでもある。",
		Legends:     []string{"Licks the scum from uncleaned bathtubs after midnight", "Startles householders who leave damp corners neglected"},
		Traits:      []string{"Long sticky tongue", "Reddish skin", "Bathroom haunt"},
		Motifs:      []string{"Hygiene", "Domestic shame", "Liminal wet spaces"},
		FunFact:     "The name literally means 'filth licker,' tying the monster directly to household cleanliness lore.",
		FunFactJA:   "名前そのものが「垢を嘗める」意味で、家の衛生譚と直結している。",
		SearchQuery: "垢嘗 妖怪 風呂",
		CreativeHooks: []string{
			"Stage a haunted sento where the akaname is the only honest cleaner.",
			"Turn a cleanliness campaign into a pact with a shy akaname.",
		},
	},
	{
		Name:        "Chochin-obake",
		NativeName:  "提灯お化け",
		Region:      "Paper lanterns across Japan",
		Category:    "Tsukumogami lantern",
		Summary:     "An aged paper lantern that sprouts a single eye and a lolling tongue, laughing as it floats through the dark.",
		SummaryJA:   "古びた提灯が目と長い舌を生やして浮かぶ付喪神。夜道や祭りの灯りに紛れて現れる。",
		Legends:     []string{"Bursts into cackling flame-light on deserted streets", "Joins processions of other animated tools"},
		Traits:      []string{"One huge eye", "Protruding tongue", "Paper-and-bamboo body"},
		Motifs:      []string{"Household objects", "Festival nights", "Playful fright"},
		FunFact:     "It is among the most iconic tsukumogami designs in ukiyo-e and modern yokai art.",
		FunFactJA:   "浮世絵から現代の妖怪画まで、付喪神の代表的なビジュアルとして親しまれている。",
		SearchQuery: "提灯お化け 付喪神",
		CreativeHooks: []string{
			"Animate a lantern parade that judges which festivals still remember old tools.",
			"Design a comedy duo of chochin-obake and karakasa-obake.",
		},
	},
	{
		Name:        "Karakasa-obake",
		NativeName:  "唐傘お化け",
		Region:      "Rainy streets and storehouses",
		Category:    "One-legged umbrella",
		Summary:     "A tattered oil-paper umbrella that hops on one leg, often with a single eye and a long tongue.",
		SummaryJA:   "古い和傘が一本足でぴょんぴょん跳ねる付喪神。一つ目に長い舌が定番の姿。",
		Legends:     []string{"Hops after people on rainy nights", "Startles passers-by then totters away laughing"},
		Traits:      []string{"Single leg", "Umbrella canopy body", "Mischievous bounce"},
		Motifs:      []string{"Rain", "Discarded tools", "Comic horror"},
		FunFact:     "Also called kasa-obake; one of the friendliest faces of the tsukumogami tradition.",
		FunFactJA:   "「傘おばけ」とも呼ばれ、付喪神のなかでも親しみやすい人気者。",
		SearchQuery: "唐傘お化け 付喪神",
		CreativeHooks: []string{
			"Write a rainy-day courier service run by karakasa-obake.",
			"Illustrate a repair shop where broken umbrellas apply to become yokai.",
		},
	},
	{
		Name:        "Bake-danuki",
		NativeName:  "化け狸",
		Region:      "Shikoku and countryside Japan",
		Category:    "Shapeshifting tanuki",
		Summary:     "Racoon-dog spirits famed for belly-drum illusions, transformation, and bawdy humour.",
		SummaryJA:   "腹鼓や変化で人を化かす狸の妖怪。徳島の金長狸など、地方英雄譚にも登場する。",
		Legends:     []string{"Transforms leaves into fake money or houses", "Drums its belly to create illusions under the moon"},
		Traits:      []string{"Round belly", "Leaf disguise", "Trickster laughter"},
		Motifs:      []string{"Transformation", "Rural wit", "Moonlit pranks"},
		FunFact:     "Unlike the often elegant kitsune, tanuki lore leans comic, earthy, and mercantile.",
		FunFactJA:   "狐が知的・神秘的に描かれがちなのに対し、狸は滑稽で商売上手なイメージが強い。",
		SearchQuery: "化け狸 伝説 金長",
		CreativeHooks: []string{
			"Plot a merchant war between a bake-danuki and a kitsune banker.",
			"Design a festival float powered by tanuki belly-drums.",
		},
	},
	{
		Name:        "Nekomata",
		NativeName:  "猫又",
		Region:      "Mountains and old towns",
		Category:    "Fork-tailed cat",
		Summary:     "An elder cat whose tail splits in two as it gains supernatural power, sometimes raising the dead or speaking human words.",
		SummaryJA:   "長い歳月を経て尻尾が二股に裂けた猫の妖怪。人語を話し、死者を操るとも伝えられる。",
		Legends:     []string{"Dances with a towel on its head like a bakeneko", "Commands corpses or curses ungrateful households"},
		Traits:      []string{"Forked tail", "Fireball tricks", "Mountain or hearth haunt"},
		Motifs:      []string{"Aging pets", "Domestic betrayal", "Necromantic rumour"},
		FunFact:     "Folklore often links nekomata to cats kept too long, feeding fear and reverence for old felines.",
		FunFactJA:   "飼い猫を長く飼うことへの畏れと敬意が、猫又譚には色濃く残る。",
		SearchQuery: "猫又 妖怪 伝承",
		CreativeHooks: []string{
			"Write a mountain tea house run by a refined nekomata medium.",
			"Stage a court case where a nekomata testifies for its late owner.",
		},
	},
	{
		Name:        "Kodama",
		NativeName:  "木霊",
		Region:      "Deep forests of Japan",
		Category:    "Tree spirit",
		Summary:     "Spirits dwelling in ancient trees; harming their host tree invites eerie echoes and misfortune.",
		SummaryJA:   "老木に宿る精霊。宿主の木を傷つけると山彦のような怪異や祟りがあるとされる。",
		Legends:     []string{"Returns a climber's call as an uncanny echo", "Marks sacred trees that villagers refuse to cut"},
		Traits:      []string{"Tree-bound presence", "Echoing voice", "Forest hush"},
		Motifs:      []string{"Animism", "Conservation", "Sacred groves"},
		FunFact:     "The word also simply means the echo in the mountains, blurring spirit and natural phenomenon.",
		FunFactJA:   "「木霊」は山の木魂であると同時に、山彦（こだま）現象の名でもある。",
		SearchQuery: "木霊 妖怪 森林",
		CreativeHooks: []string{
			"Design a logging drama where every felled tree releases a kodama contract.",
			"Compose a silent forest level where only kodama echoes guide the player.",
		},
	},
	{
		Name:        "Yamauba",
		NativeName:  "山姥",
		Region:      "Remote mountain depths",
		Category:    "Mountain crone",
		Summary:     "An old woman of the deep mountains who may devour travellers—or foster heroes and share secret knowledge.",
		SummaryJA:   "深山に住む老女の妖怪。人を喰らう恐怖の存在でもあり、英雄を育て知恵を授ける面もある。",
		Legends:     []string{"Offers shelter then reveals monstrous hunger", "Raises abandoned children into legendary warriors"},
		Traits:      []string{"White hair", "Mountain hut", "Ambiguous hospitality"},
		Motifs:      []string{"Liminal motherhood", "Wilderness", "Dual nature"},
		FunFact:     "Some traditions link yamauba to childbirth deities and spinning, not only cannibal terror.",
		FunFactJA:   "産育や機織りと結びつく伝承もあり、単なる人食い鬼婆に留まらない。",
		SearchQuery: "山姥 民話 山",
		CreativeHooks: []string{
			"Write a yamauba midwife who prices her aid in years of memory.",
			"Retell a hero origin as a reluctant apprenticeship to a yamauba.",
		},
	},
	{
		Name:        "Oni",
		NativeName:  "鬼",
		Region:      "Throughout Japan",
		Category:    "Horned demon",
		Summary:     "Horned, fang-mouthed beings of immense strength—villains of Setsubun, guardians of hell, and symbols of raw power.",
		SummaryJA:   "角と牙、虎柄のパンツが典型の鬼。節分の悪役、地獄の獄卒、力の象徴と多面的に語られる。",
		Legends:     []string{"Driven out with roasted soybeans at Setsubun", "Serves as underworld jailers or mountain bandits"},
		Traits:      []string{"Horns", "Iron clubs", "Fearsome bulk"},
		Motifs:      []string{"Expulsion rites", "Moral extremes", "Raw strength"},
		FunFact:     "Calling someone an 'oni' can mean cruel villain or awe-inspiring tough person, depending on tone.",
		FunFactJA:   "「鬼のような」は冷酷さも、畏れ多い強さも表せる両義的な言葉。",
		SearchQuery: "鬼 民話 節分",
		CreativeHooks: []string{
			"Reimagine Setsubun from the oni side of the door.",
			"Design an oni blacksmith who forges clubs that only the pure can lift.",
		},
	},
	{
		Name:        "Shuten-doji",
		NativeName:  "酒呑童子",
		Region:      "Ooe-yama near Kyoto",
		Category:    "Demon lord",
		Summary:     "A sake-loving oni chieftain who abducted nobles until Minamoto no Raiko's band defeated him.",
		SummaryJA:   "酒を愛する鬼の頭領。京の姫をさらい、源頼光一行に大江山で討たれたと伝えられる。",
		Legends:     []string{"Feasts on captives atop Mount Ooe", "Is tricked by poisoned sake and divine disguises"},
		Traits:      []string{"Youthful demon face", "Bottomless thirst", "Oni retinue"},
		Motifs:      []string{"Decadence", "Heroic conquest", "Capital vs wilds"},
		FunFact:     "His severed head legendarily bit at Raiko even after death—a final act of demonic will.",
		FunFactJA:   "切り落とされた首がなお頼光に噛みついた、という凄惨な後日談も残る。",
		SearchQuery: "酒呑童子 大江山 源頼光",
		CreativeHooks: []string{
			"Stage a diplomatic banquet where the only safe toast is a lie.",
			"Write Shuten-doji as a fallen host who still keeps perfect guest etiquette.",
		},
	},
	{
		Name:        "Nurarihyon",
		NativeName:  "ぬらりひょん",
		Region:      "Seto Inland Sea region and beyond",
		Category:    "Slippery overlord",
		Summary:     "A slippery-headed elder who slips into homes as if he owns them; later tales call him the supreme commander of yokai.",
		SummaryJA:   "ぬるりとした頭の老人が、いつの間にか上がり込む妖怪。後世では妖怪の総大将とも称される。",
		Legends:     []string{"Enters a house and calmly drinks tea as the master", "Leads night processions of lesser yokai in modern retellings"},
		Traits:      []string{"Gourd-like head", "Unhurried gait", "Social intrusion"},
		Motifs:      []string{"Authority", "Liminal guests", "Who belongs"},
		FunFact:     "The name suggests something that slips from the grasp—hard to pin down, harder to expel.",
		FunFactJA:   "名前は「ぬらりと捉まえどころがない」響きで、正体の掴みにくさを表す。",
		SearchQuery: "ぬらりひょん 妖怪 総大将",
		CreativeHooks: []string{
			"Write a home-invasion story where the intruder has better manners than the owners.",
			"Design a yokai parliament chaired by an unflappable nurarihyon.",
		},
	},
	{
		Name:        "Tofu-kozo",
		NativeName:  "豆腐小僧",
		Region:      "Edo streets and towns",
		Category:    "Tofu boy",
		Summary:     "A bashful boyish yokai who offers a tray of tofu; more endearing than dangerous in most tales.",
		SummaryJA:   "豆腐をのせた盆を持つ童子の妖怪。悪さより愛嬌が勝り、江戸の町っ子的な人気者。",
		Legends:     []string{"Appears on rainy nights with a block of tofu", "Sometimes flavours the tofu with a drop of nose-drip in comic prints—an old joke"},
		Traits:      []string{"Paper umbrella", "Tofu tray", "Child stature"},
		Motifs:      []string{"Urban folklore", "Comic relief", "Street life"},
		FunFact:     "He became especially popular in Edo-period illustrated books as a 'mascot' yokai.",
		FunFactJA:   "江戸時代の絵本でマスコット的に量産され、親しみやすい妖怪像を定着させた。",
		SearchQuery: "豆腐小僧 江戸 妖怪",
		CreativeHooks: []string{
			"Open a midnight tofu stand staffed only by tofu-kozo.",
			"Write a buddy comedy of tofu-kozo and karakasa-obake delivering in the rain.",
		},
	},
	{
		Name:        "Konaki-jiji",
		NativeName:  "子泣き爺",
		Region:      "Shikoku mountain paths",
		Category:    "Crying elder infant",
		Summary:     "A yokai that cries like a baby until picked up, then becomes crushing stone-heavy in the carrier's arms.",
		SummaryJA:   "赤ん坊のように泣いて背負わせ、急に石のように重くなって押し潰す四国などの妖怪。",
		Legends:     []string{"Lures kind travellers with infant wails", "Grows impossibly heavy once held"},
		Traits:      []string{"Baby voice", "Elder face", "Crushing weight"},
		Motifs:      []string{"False vulnerability", "Mountain trails", "Kindness tested"},
		FunFact:     "The horror flips compassion into trap—classic 'beware the too-perfect victim' folklore.",
		FunFactJA:   "優しさが罠になる構造は、道中怪談の定番モチーフ。",
		SearchQuery: "子泣き爺 四国 妖怪",
		CreativeHooks: []string{
			"Invert the tale: a konaki-jiji who only grows light for the truly exhausted.",
			"Design a stamina mechanic based on refusing or accepting the crying burden.",
		},
	},
	{
		Name:        "Ubume",
		NativeName:  "産女",
		Region:      "Riversides and bridges nationwide",
		Category:    "Birth spirit",
		Summary:     "The spirit of a woman who died in childbirth, often asking passers-by to hold her baby—sometimes a blessing, sometimes a trial.",
		SummaryJA:   "産で死んだ女の霊。赤子を託し、銭や福を残す話も、重みで試す話もある。",
		Legends:     []string{"Hands a baby to a traveller on a bridge", "Leaves gold or vanishes once the child is carried home"},
		Traits:      []string{"Blood-stained robe", "Infant in arms", "Waterside haunt"},
		Motifs:      []string{"Maternal grief", "Charity", "Liminal birth"},
		FunFact:     "Related to Chinese guhuoniao lore, but thoroughly naturalized in Japanese kaidan.",
		FunFactJA:   "中国の姑獲鳥譚とも響き合うが、日本の川辺怪談として深く土着化している。",
		SearchQuery: "産女 怪談 伝承",
		CreativeHooks: []string{
			"Write a midwife who bargains with ubume to save living mothers.",
			"Compose a bridge scene where the 'baby' is the traveller's unborn future.",
		},
	},
	{
		Name:        "Nure-onna",
		NativeName:  "濡女",
		Region:      "Coasts and riverbanks",
		Category:    "Wet woman",
		Summary:     "A soaked, long-haired woman of the shore—sometimes serpentine—who may offer a child that becomes a crushing stone.",
		SummaryJA:   "濡れた長い髪の女の妖怪。蛇体とも言われ、赤子を持たせて重みで沈める話がある。",
		Legends:     []string{"Appears dripping wet with an infant bundle", "Reveals snake-like true form at the waterline"},
		Traits:      []string{"Soaked hair", "Shoreline presence", "Deadly gift"},
		Motifs:      []string{"Water borders", "Feminine dread", "False charity"},
		FunFact:     "Often grouped with iso-onna; regional names blur wet-woman and serpent-woman tales.",
		FunFactJA:   "磯女と混同・隣接する伝承が多く、地域で名前と姿が入れ替わる。",
		SearchQuery: "濡女 妖怪 海",
		CreativeHooks: []string{
			"Stage a lighthouse keeper's pact with a nure-onna tide calendar.",
			"Write a rescue story where drying her hair is the only safe kindness.",
		},
	},
	{
		Name:        "Jorogumo",
		NativeName:  "絡新婦",
		Region:      "Mountain waterfalls and forests",
		Category:    "Binding bride spider",
		Summary:     "A giant spider that takes the form of a captivating woman to lure victims into silken traps.",
		SummaryJA:   "美しい女に化けた巨大蜘蛛。男を誘って糸で縛り、喰らう山中の妖怪。",
		Legends:     []string{"Plays biwa or lures travellers near waterfalls", "Binds prey in threads strong as rope"},
		Traits:      []string{"Spider true form", "Alluring disguise", "Silk snares"},
		Motifs:      []string{"Seduction", "Predator beauty", "Hidden nature"},
		FunFact:     "The name can be read as 'woman-spider' or linked to 'entangling bride.'",
		FunFactJA:   "「絡めて縛る蜘蛛」と「婦」の字が重なり、美しさと危険が名前に宿る。",
		SearchQuery: "絡新婦 蜘蛛 妖怪",
		CreativeHooks: []string{
			"Design a tea ceremony whose etiquette is actually web geometry.",
			"Write a romance where both lovers know the other is wearing a disguise.",
		},
	},
	{
		Name:        "Tsuchigumo",
		NativeName:  "土蜘蛛",
		Region:      "Yamato and classical chronicles",
		Category:    "Earth spider",
		Summary:     "An ancient label for rebellious or othered mountain peoples, later pictured as monstrous ground-spiders.",
		SummaryJA:   "古くは山の異族や反逆者を指した名が、後に巨大な土中の蜘蛛の怪物像となった。",
		Legends:     []string{"Lurks in mounds and caverns in warrior legends", "Fought by heroes like Minamoto no Yorimitsu in later art"},
		Traits:      []string{"Sprawling spider limbs", "Earth burrows", "Classical dread"},
		Motifs:      []string{"Othering", "Hero myths", "Land spirits"},
		FunFact:     "Reading tsuchigumo lore means reading how centres named their margins as monsters.",
		FunFactJA:   "中央が周縁を「怪物化」して語った歴史を、そのまま残す存在でもある。",
		SearchQuery: "土蜘蛛 伝説 大和",
		CreativeHooks: []string{
			"Retell a tsuchigumo siege from the cavern side.",
			"Map a city built atop sealed spider mounds that still hum at night.",
		},
	},
	{
		Name:        "Wanyudo",
		NativeName:  "輪入道",
		Region:      "Kyoto streets and highways",
		Category:    "Wheel monk",
		Summary:     "A flaming ox-cart wheel bearing a tormented human face, said to snatch the souls of those who stare.",
		SummaryJA:   "炎をまとう車輪に人の顔がついた妖怪。見ると魂を抜き取られるとも言われる京の怪異。",
		Legends:     []string{"Rolls through midnight avenues trailing fire", "Punishes the curious who meet its gaze"},
		Traits:      []string{"Burning wheel", "Agonized face", "Soul-stealing stare"},
		Motifs:      []string{"Karma", "Urban night", "Forbidden looking"},
		FunFact:     "Often explained as a transformed wicked priest or a damned soul bound to the wheel.",
		FunFactJA:   "悪僧や罪人が車輪の刑・業の炎と結びついた姿、と解釈されることが多い。",
		SearchQuery: "輪入道 京都 妖怪",
		CreativeHooks: []string{
			"Write traffic rules for a city where wanyudo owns the night lanes.",
			"Design a boss fight where looking away is both shield and vulnerability.",
		},
	},
	{
		Name:        "Satori",
		NativeName:  "覚",
		Region:      "Hida and Kai mountain ranges",
		Category:    "Mind-reading ape",
		Summary:     "An ape-like mountain yokai that voices a traveller's thoughts aloud, leaving no privacy of mind.",
		SummaryJA:   "人の心を先読みして声に出す猿に似た山の妖怪。考えが筒抜けになる恐怖を与える。",
		Legends:     []string{"Repeats a hiker's unspoken fears from the treeline", "Loses interest if the mind becomes truly empty"},
		Traits:      []string{"Simian shape", "Thought-speech", "Forest stalker"},
		Motifs:      []string{"Privacy", "Self-awareness", "Mountain solitude"},
		FunFact:     "Some tellings say emptying the mind or accepting the exposure drives the satori away.",
		FunFactJA:   "無心になる、あるいは見透かされることを受け入れると去る、という対処譚もある。",
		SearchQuery: "覚 妖怪 飛騨",
		CreativeHooks: []string{
			"Write a therapy session conducted entirely by a satori.",
			"Design a stealth game where noise is thought, not footsteps.",
		},
	},
	{
		Name:        "Dorotabo",
		NativeName:  "泥田坊",
		Region:      "Abandoned rice paddies",
		Category:    "Muddy field wraith",
		Summary:     "A three-fingered muddy figure that rises from neglected paddies crying 'give me back my field!'",
		SummaryJA:   "荒れた田から「田を返せ」と立ち上がる三つ指の泥人形のような妖怪。",
		Legends:     []string{"Emerges from waterlogged paddies at night", "Accuses those who wasted or stole farmland"},
		Traits:      []string{"Mud body", "Three fingers", "Paddy haunt"},
		Motifs:      []string{"Agriculture", "Neglect", "Land rights"},
		FunFact:     "A yokai of rural conscience—fields are living relationships, not just plots.",
		FunFactJA:   "田畑を人間と土地の関係として見る農村倫理が、姿を借りて現れた存在。",
		SearchQuery: "泥田坊 田 妖怪",
		CreativeHooks: []string{
			"Stage a land-reform hearing interrupted by dorotabo witnesses.",
			"Design a farming sim where neglected tiles spawn dorotabo.",
		},
	},
	{
		Name:        "Mokumokuren",
		NativeName:  "目目連",
		Region:      "Dilapidated houses",
		Category:    "Eyes in the shoji",
		Summary:     "Countless eyes that open across torn paper screens in empty rooms—watching without a body.",
		SummaryJA:   "破れた障子や壁に無数の目が浮かぶ屋敷の怪異。体はなく、視線だけが部屋を満たす。",
		Legends:     []string{"Manifests in abandoned parlours after dark", "Vanishes if the screens are carefully repaired in some tales"},
		Traits:      []string{"Shoji eyes", "Silent watching", "Ruin aesthetic"},
		Motifs:      []string{"Surveillance", "Decay", "Household neglect"},
		FunFact:     "A perfect image of 'the house still looking back' after people leave.",
		FunFactJA:   "人が去ったあとも「家が見ている」感覚を、視覚イメージにした妖怪。",
		SearchQuery: "目目連 障子 妖怪",
		CreativeHooks: []string{
			"Write an architecture critique narrated only by mokumokuren.",
			"Design a puzzle room where closing eyes on screens changes the map.",
		},
	},
	{
		Name:        "Aoandon",
		NativeName:  "青行燈",
		Region:      "Hyakumonogatari gatherings",
		Category:    "Blue lantern spectre",
		Summary:     "The blue-flamed spirit said to appear when the hundredth kaidan is told and the final light goes out.",
		SummaryJA:   "百物語の最後、青く燃える行灯に現れるとされる女の妖怪。語りの結界を破る存在。",
		Legends:     []string{"Appears as the final candle or andon is extinguished", "Listens to a hundred ghost stories as invitation"},
		Traits:      []string{"Blue flame", "Pale woman", "Story-bound arrival"},
		Motifs:      []string{"Storytelling ritual", "Threshold of night", "Narrative magic"},
		FunFact:     "Whether or not she 'truly' came, aoandon names the chill at the end of a successful hyakumonogatari.",
		FunFactJA:   "実在譚というより、百物語が成功したときの「最後の恐怖」に名前を与えた存在。",
		SearchQuery: "青行燈 百物語 妖怪",
		CreativeHooks: []string{
			"Host a hyakumonogatari livestream whose chat summons aoandon.",
			"Write the hundredth story as the only one aoandon fears.",
		},
	},
	{
		Name:        "Tamamo-no-Mae",
		NativeName:  "玉藻前",
		Region:      "Imperial court and Nasu plain",
		Category:    "Nine-tailed courtesan",
		Summary:     "A legendary fox spirit who infiltrated the court as a brilliant beauty, later revealed and pursued to the Killing Stone.",
		SummaryJA:   "絶世の美女として宮中に仕えた白面金毛九尾の狐。正体がばれ、那須の殺生石へと続く。",
		Legends:     []string{"Charms the emperor with unmatched learning and grace", "Flees as a fox and becomes the poisonous Sessho-seki"},
		Traits:      []string{"Nine tails", "Courtly brilliance", "Deadly glamour"},
		Motifs:      []string{"Political intrigue", "Feminine power", "Sacred contamination"},
		FunFact:     "Her legend knits Chinese fox-lore to Japanese court history and the Nasu landscape.",
		FunFactJA:   "中国の狐精譚と日本の宮廷史・那須の土地が一本の物語に結ばれている。",
		SearchQuery: "玉藻前 九尾 殺生石",
		CreativeHooks: []string{
			"Rewrite the court arc as a tragedy of a fox who genuinely loved scholarship.",
			"Design a pilgrimage route of sites that still 'remember' Tamamo's flight.",
		},
	},
	{
		Name:        "Kiyohime",
		NativeName:  "清姫",
		Region:      "Kino River and Dojo-ji, Kii",
		Category:    "Serpent of obsession",
		Summary:     "A woman whose unrequited love for the monk Anchin transformed her into a fiery serpent that burned him inside the temple bell.",
		SummaryJA:   "安珍を慕った女が執着の果てに蛇体と化し、道成寺の鐘の中の彼を焼き殺した物語の主人公。",
		Legends:     []string{"Pursues Anchin along the Kino River", "Coils around the temple bell in flames of jealousy"},
		Traits:      []string{"Serpent transformation", "Relentless pursuit", "Temple bell climax"},
		Motifs:      []string{"Desire", "Jealousy", "Sacred space violated"},
		FunFact:     "The Dojo-ji legend became Noh, Kabuki, and dance—obsession staged as art for centuries.",
		FunFactJA:   "能・歌舞伎・日本舞踊で繰り返し上演され、執着の物語が芸能として洗練された。",
		SearchQuery: "清姫 道成寺 安珍",
		CreativeHooks: []string{
			"Tell the story from the bell's point of view.",
			"Write a modern Kiyohime who tracks read receipts instead of river fords.",
		},
	},
	{
		Name:        "Hashihime",
		NativeName:  "橋姫",
		Region:      "Uji and other bridges",
		Category:    "Bridge princess",
		Summary:     "A spirit of the bridge—jealous guardian or cursed woman—who polices crossings and unfaithful hearts.",
		SummaryJA:   "橋にまつわる女の霊・神。嫉妬や呪い、通行の境界を司る存在として語られる。",
		Legends:     []string{"Curses rivals in love from the bridge railing", "Appears as a noble woman waiting at midnight on the planks"},
		Traits:      []string{"Bridge haunt", "Jealous power", "Boundary watch"},
		Motifs:      []string{"Thresholds", "Envy", "Water crossings"},
		FunFact:     "The Uji Hashihime is also woven into classical poetry and The Tale of Genji's world.",
		FunFactJA:   "宇治の橋姫は古典文学・和歌の世界とも結びつき、単なる妖怪に留まらない。",
		SearchQuery: "橋姫 宇治 伝説",
		CreativeHooks: []string{
			"Design a bridge that only forgives those who admit envy.",
			"Write Hashihime as infrastructure—she is the toll of every crossing.",
		},
	},
	{
		Name:        "Funa-yurei",
		NativeName:  "船幽霊",
		Region:      "Coastal waters of Japan",
		Category:    "Ship ghosts",
		Summary:     "Spirits of the drowned who approach boats asking for a ladle—then try to swamp the vessel with seawater.",
		SummaryJA:   "海難死者の霊が船に近寄り柄杓を求める。渡すと水を無限に汲み入れ船を沈めるという。",
		Legends:     []string{"Beg for hishaku ladles in the fog", "Are foiled by ladles with holes, a sailor's countermeasure"},
		Traits:      []string{"Wet funerary look", "Fleet of phantom boats", "Fog at sea"},
		Motifs:      []string{"Maritime death", "Sailor cunning", "Fog"},
		FunFact:     "The holed-ladle trick is one of folklore's neatest practical defenses.",
		FunFactJA:   "底に穴を開けた柄杓を渡す、という対処法が航海民俗として広く知られる。",
		SearchQuery: "船幽霊 海難 伝承",
		CreativeHooks: []string{
			"Write a coast guard manual co-authored with funa-yurei.",
			"Design a fog level where every request for tools is a moral test.",
		},
	},
	{
		Name:        "Mikoshi-nyudo",
		NativeName:  "見越入道",
		Region:      "Roads and night paths nationwide",
		Category:    "Look-over monk",
		Summary:     "A towering nyudo whose height grows as you look up; saying 'mikoshita' (I saw over you) is said to defeat it.",
		SummaryJA:   "見上げるほど高く伸びる入道。『見越した』と言い放つと消える、という対処譚が有名。",
		Legends:     []string{"Rises endlessly if you crane your neck in fear", "Collapses when addressed with the correct formula"},
		Traits:      []string{"Elongating body", "Monk-like head", "Roadblock terror"},
		Motifs:      []string{"Perspective", "Courage formulas", "Night travel"},
		FunFact:     "A cousin to hitotsume-nyudo lore—size and gaze are the weapons.",
		FunFactJA:   "一つ目入道譚とも隣接し、「見る／見られる」が戦いの核心になる。",
		SearchQuery: "見越入道 妖怪 道中",
		CreativeHooks: []string{
			"Build a VR horror where looking up is the resource you must budget.",
			"Write a comedy of manners about the exact politeness level of 'mikoshita'.",
		},
	},
	{
		Name:        "Azuki-arai",
		NativeName:  "小豆洗い",
		Region:      "Rivers and forest streams",
		Category:    "Bean washer",
		Summary:     "An unseen presence that washes azuki beans in a stream, the rhythmic sound unnerving travellers.",
		SummaryJA:   "川辺で小豆を洗う音だけを立て、姿を見せぬことが多い怪異。音が人を不安にさせる。",
		Legends:     []string{"Produces endless washing sounds at dusk", "Sometimes appears as a small hunched figure by the water"},
		Traits:      []string{"Auditory haunt", "Riverside", "Unseen labour"},
		Motifs:      []string{"Sound horror", "Rural night", "Invisible work"},
		FunFact:     "Related azuki-hakari lore moves the same uncanny measuring sound into attics.",
		FunFactJA:   "天井裏で小豆を量る「小豆はかり」と音の怪異として姉妹関係にある。",
		SearchQuery: "小豆洗い 妖怪 川",
		CreativeHooks: []string{
			"Score a film using only azuki-arai rhythms as the threat.",
			"Write a foodways tale where the beans are souls being rinsed clean.",
		},
	},
	{
		Name:        "Kuchisake-onna",
		NativeName:  "口裂け女",
		Region:      "Urban Japan since the late 1970s",
		Category:    "Slit-mouthed woman",
		Summary:     "A masked woman who asks 'Am I pretty?' then reveals a mouth slit ear to ear—a modern urban legend turned yokai icon.",
		SummaryJA:   "マスクの下に耳まで裂けた口。『あたし、きれい？』と問う昭和後期発の都市伝説的妖怪。",
		Legends:     []string{"Stops children and adults with a beauty question", "Pursues those who answer badly—or sometimes any answer at all"},
		Traits:      []string{"Surgical mask", "Scissors or knife", "Urban night"},
		Motifs:      []string{"Beauty pressure", "Rumour panic", "Modern folklore"},
		FunFact:     "She shows that yokai culture still births new figures from mass media and schoolyard fear.",
		FunFactJA:   "マスメディアと学校の噂から新しい「妖怪」が生まれる、現代民俗の好例。",
		SearchQuery: "口裂け女 都市伝説",
		CreativeHooks: []string{
			"Rewrite the question as a critique of beauty economies.",
			"Design a branching dialogue where every answer rewrites the city map.",
		},
	},
	{
		Name:        "Inugami",
		NativeName:  "犬神",
		Region:      "Shikoku and western Japan",
		Category:    "Dog spirit possession",
		Summary:     "A canine spirit used in possession rites and family curses—feared as a hereditary tsukimono.",
		SummaryJA:   "犬の霊を使役する憑きもの。家系に付き、祟りや呪詛と結びついて恐れられた。",
		Legends:     []string{"Possesses victims on behalf of a controlling household", "Is bound and inherited through secret family rites"},
		Traits:      []string{"Invisible dog spirit", "Possession illness", "Household secrecy"},
		Motifs:      []string{"Witchcraft accusations", "Kinship fear", "Western Japan lore"},
		FunFact:     "Inugami belief intersected with real social stigma against certain lineages.",
		FunFactJA:   "特定家系への差別や猜疑と歴史的に絡んできた、重い民俗でもある。",
		SearchQuery: "犬神 憑きもの 四国",
		CreativeHooks: []string{
			"Write a legal drama about proving an inugami curse in court.",
			"Design a family saga where breaking the inugami bond is the inheritance.",
		},
	},
	{
		Name:        "Raiju",
		NativeName:  "雷獣",
		Region:      "Storms across Japan",
		Category:    "Thunder beast",
		Summary:     "A beast that falls with lightning—cat-, weasel-, or wolf-like—and may nest in a human navel in odd medical folklore.",
		SummaryJA:   "雷とともに落ちる獣。猫や鼬に似るとも言われ、奇妙な医譚では人の臍に入る話もある。",
		Legends:     []string{"Rides thunderbolts into trees and rooftops", "Is blamed for strange burns and storm damage"},
		Traits:      []string{"Lightning companion", "Sharp claws", "Storm scent"},
		Motifs:      []string{"Weather", "Sudden violence", "Body folklore"},
		FunFact:     "Edo naturalists sometimes treated raiju as a 'real' animal to be catalogued.",
		FunFactJA:   "江戸時代には実在の動物として図譜に載せようとする試みもあった。",
		SearchQuery: "雷獣 雷 妖怪",
		CreativeHooks: []string{
			"Write a storm chaser who tags raiju like lightning sprites.",
			"Design a roof-repair guild that bargains with nesting raiju.",
		},
	},
	{
		Name:        "Hitotsume-kozo",
		NativeName:  "一つ目小僧",
		Region:      "Towns and temples nationwide",
		Category:    "One-eyed boy",
		Summary:     "A child-sized monk-like yokai with a single large eye—startling rather than murderous in many tellings.",
		SummaryJA:   "大きな一つ目の童子僧のような妖怪。驚かせる悪戯が多く、即凶というほどでもない話も。",
		Legends:     []string{"Pops out on dark streets to shock pedestrians", "Is tied to calendrical and omen lore in some regions"},
		Traits:      []string{"Single eye", "Boyish monk look", "Sudden appearance"},
		Motifs:      []string{"Omen", "Playful scare", "Urban night"},
		FunFact:     "Some New Year customs once linked hitotsume imagery to warding or calendar rites.",
		FunFactJA:   "地方によっては暦や厄除けの風習と一つ目の童子像が結びついた。",
		SearchQuery: "一つ目小僧 妖怪",
		CreativeHooks: []string{
			"Make a detective whose only witness is a hitotsume-kozo.",
			"Design stickers that are actually tiny hitotsume wards.",
		},
	},
	{
		Name:        "Ibaraki-doji",
		NativeName:  "茨木童子",
		Region:      "Kyoto and Ooe-yama",
		Category:    "Oni lieutenant",
		Summary:     "A fierce oni of Shuten-doji's circle, famed for the Rashomon arm-severing duel with Watanabe no Tsuna.",
		SummaryJA:   "酒呑童子配下の鬼。羅生門で渡辺綱と闘し、腕を斬られる逸話で知られる。",
		Legends:     []string{"Lurks at Rashomon gate in classical warrior tales", "Reclaims a severed arm through cunning disguise"},
		Traits:      []string{"Oni strength", "Gate haunt", "Cunning revenge"},
		Motifs:      []string{"Capital gates", "Heroic combat", "Disguise"},
		FunFact:     "The arm episode is pure stage gold—Noh and Kabuki never tired of it.",
		FunFactJA:   "腕の奪回エピソードは能・歌舞伎で繰り返し上演される人気場面。",
		SearchQuery: "茨木童子 羅生門 渡辺綱",
		CreativeHooks: []string{
			"Retell Rashomon as a security night-shift gone supernatural.",
			"Write Ibaraki-doji mourning the politics of being only second-in-command.",
		},
	},
	{
		Name:        "Ningyo",
		NativeName:  "人魚",
		Region:      "Coastal Japan and classical texts",
		Category:    "Merfolk",
		Summary:     "Human-faced fish beings; tasting their flesh is said to grant extraordinary longevity, as in the Yao Bikuni legend.",
		SummaryJA:   "人面魚体の存在。肉を食べると不老長寿になる、という八百比丘尼伝説が有名。",
		Legends:     []string{"Is caught by fishermen who regret the meal's consequences", "Links to nun Yao Bikuni's centuries-long life"},
		Traits:      []string{"Fish body", "Human face", "Longevity curse-gift"},
		Motifs:      []string{"Immortality", "Sea bounty", "Tragic long life"},
		FunFact:     "Ningyo omens could also foretell storms or upheaval when washed ashore.",
		FunFactJA:   "漂着した人魚は嵐や世の乱れの前兆ともされ、吉凶両面で語られた。",
		SearchQuery: "人魚 八百比丘尼 伝承",
		CreativeHooks: []string{
			"Write immortality as a paperwork problem for a ningyo-eater.",
			"Design a coastal museum that is secretly a ningyo retirement home.",
		},
	},
	{
		Name:        "Tsukumogami",
		NativeName:  "付喪神",
		Region:      "Household Japan after long use",
		Category:    "Tool spirits",
		Summary:     "Objects that gain spirit after a hundred years of use—umbrellas, tools, clothes—demanding respect for things.",
		SummaryJA:   "百年使った道具に魂が宿るという付喪神。物を粗末にすると化けて出る、という倫理でもある。",
		Legends:     []string{"Rise en masse in picture scrolls as rebellious tools", "Individually star as chochin-obake, karakasa, bakezori, and more"},
		Traits:      []string{"Animated objects", "Centenarian tools", "Comic or vengeful mood"},
		Motifs:      []string{"Material culture", "Waste", "Respect for things"},
		FunFact:     "Tsukumogami is a category as much as a creature—Japan's mythology of stuff.",
		FunFactJA:   "個体名というより「物の妖怪」カテゴリそのもので、日本的な物への感覚を映す。",
		SearchQuery: "付喪神 百器徒然袋",
		CreativeHooks: []string{
			"Write a recycling center that negotiates labor contracts with tsukumogami.",
			"Design a dungeon where every weapon remembers its previous owners.",
		},
	},
}
